#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using LSDW.Presentation.Properties;

namespace LSDW.Presentation.Menus;

internal sealed partial class SettingsMenu
{
	private void AddMenuItems()
	{
		var listItemDownTimeInHours = AddListItem(
			Resources.UI_Settings_Dealer_DownTimeInHours_Title,
			Resources.UI_Settings_Dealer_DownTimeInHours_Description,
			(item, index) => { _settingsService.Dealer.DownTimeInHours.Value = item; },
			_settingsService.Dealer.GetDownTimeInHoursValues()
			);

		_settingsService.Dealer.DownTimeInHours.ValueChanged += (sender, args)
			=> { listItemDownTimeInHours.SelectedItem = args.NewValue; };

		var checkBoxHasArmor = AddCheckbox(
			Resources.UI_Settings_Dealer_HasArmor_Title,
			Resources.UI_Settings_Dealer_HasArmor_Description,
			_settingsService.Dealer.HasArmor.Value,
			changed => { _settingsService.Dealer.HasArmor.Value = changed; });
		
		_settingsService.Dealer.HasArmor.ValueChanged += (sender, args)
			=> { checkBoxHasArmor.Checked = args.NewValue; };
			
		var checkBoxHasWeapons = AddCheckbox(
			Resources.UI_Settings_Dealer_HasWeapons_Title,
			Resources.UI_Settings_Dealer_HasWeapons_Description,
			_settingsService.Dealer.HasWeapons.Value,
			changed => { _settingsService.Dealer.HasWeapons.Value = changed; });
		
		_settingsService.Dealer.HasWeapons.ValueChanged += (sender, args)
			=> { checkBoxHasWeapons.Checked = args.NewValue; };
			
		var listItemInventoryChangeInterval = AddListItem(
			Resources.UI_Settings_Market_InventoryChangeInterval_Title,
			Resources.UI_Settings_Market_InventoryChangeInterval_Description,
			(item, index) => { _settingsService.Market.InventoryChangeInterval.Value = item; },
			_settingsService.Market.GetInventoryChangeIntervalValues()
			);

		_settingsService.Market.InventoryChangeInterval.ValueChanged += (sender, args)
			=> { listItemInventoryChangeInterval.SelectedItem = args.NewValue; };

		var listItemMaximumDrugPrice = AddListItem(
			Resources.UI_Settings_Market_MaximumDrugPrice_Title,
			Resources.UI_Settings_Market_MaximumDrugPrice_Description,
			(item, index) => { _settingsService.Market.MaximumDrugPrice.Value = item; },
			_settingsService.Market.GetMaximumDrugPriceValues()
			);

		_settingsService.Market.MaximumDrugPrice.ValueChanged += (sender, args)
			=> { listItemMaximumDrugPrice.SelectedItem = args.NewValue; };

		var listItemMinimumDrugPrice = AddListItem(
			Resources.UI_Settings_Market_MinimumDrugPrice_Title,
			Resources.UI_Settings_Market_MinimumDrugPrice_Description,
			(item, index) => { _settingsService.Market.MinimumDrugPrice.Value = item; },
			_settingsService.Market.GetMinimumDrugPriceValues()
			);

		_settingsService.Market.MinimumDrugPrice.ValueChanged += (sender, args)
			=> { listItemMinimumDrugPrice.SelectedItem = args.NewValue; };

		var listItemPriceChangeInterval = AddListItem(
			Resources.UI_Settings_Market_PriceChangeInterval_Title,
			Resources.UI_Settings_Market_PriceChangeInterval_Description,
			(item, index) => { _settingsService.Market.PriceChangeInterval.Value = item; },
			_settingsService.Market.GetPriceChangeIntervalValues()
			);

		_settingsService.Market.PriceChangeInterval.ValueChanged += (sender, args)
			=> { listItemPriceChangeInterval.SelectedItem = args.NewValue; };

		var listItemSpecialOfferChance = AddListItem(
			Resources.UI_Settings_Market_SpecialOfferChance_Title,
			Resources.UI_Settings_Market_SpecialOfferChance_Description,
			(item, index) => { _settingsService.Market.SpecialOfferChance.Value = item; },
			_settingsService.Market.GetSpecialOfferChanceValues()
			);

		_settingsService.Market.SpecialOfferChance.ValueChanged += (sender, args)
			=> { listItemSpecialOfferChance.SelectedItem = args.NewValue; };

		var listItemExperienceMultiplier = AddListItem(
			Resources.UI_Settings_Player_ExperienceMultiplier_Title,
			Resources.UI_Settings_Player_ExperienceMultiplier_Description,
			(item, index) => { _settingsService.Player.ExperienceMultiplier.Value = item; },
			_settingsService.Player.GetExperienceMultiplierValues()
			);

		_settingsService.Player.ExperienceMultiplier.ValueChanged += (sender, args)
			=> { listItemExperienceMultiplier.SelectedItem = args.NewValue; };

		var listItemInventoryExpansionPerLevel = AddListItem(
			Resources.UI_Settings_Player_InventoryExpansionPerLevel_Title,
			Resources.UI_Settings_Player_InventoryExpansionPerLevel_Description,
			(item, index) => { _settingsService.Player.InventoryExpansionPerLevel.Value = item; },
			_settingsService.Player.GetInventoryExpansionPerLevelValues()
			);

		_settingsService.Player.InventoryExpansionPerLevel.ValueChanged += (sender, args)
			=> { listItemInventoryExpansionPerLevel.SelectedItem = args.NewValue; };

		var checkBoxLooseDrugsOnDeath = AddCheckbox(
			Resources.UI_Settings_Player_LooseDrugsOnDeath_Title,
			Resources.UI_Settings_Player_LooseDrugsOnDeath_Description,
			_settingsService.Player.LooseDrugsOnDeath.Value,
			changed => { _settingsService.Player.LooseDrugsOnDeath.Value = changed; });
		
		_settingsService.Player.LooseDrugsOnDeath.ValueChanged += (sender, args)
			=> { checkBoxLooseDrugsOnDeath.Checked = args.NewValue; };
			
		var checkBoxLooseDrugsWhenBusted = AddCheckbox(
			Resources.UI_Settings_Player_LooseDrugsWhenBusted_Title,
			Resources.UI_Settings_Player_LooseDrugsWhenBusted_Description,
			_settingsService.Player.LooseDrugsWhenBusted.Value,
			changed => { _settingsService.Player.LooseDrugsWhenBusted.Value = changed; });
		
		_settingsService.Player.LooseDrugsWhenBusted.ValueChanged += (sender, args)
			=> { checkBoxLooseDrugsWhenBusted.Checked = args.NewValue; };
			
		var checkBoxLooseMoneyOnDeath = AddCheckbox(
			Resources.UI_Settings_Player_LooseMoneyOnDeath_Title,
			Resources.UI_Settings_Player_LooseMoneyOnDeath_Description,
			_settingsService.Player.LooseMoneyOnDeath.Value,
			changed => { _settingsService.Player.LooseMoneyOnDeath.Value = changed; });
		
		_settingsService.Player.LooseMoneyOnDeath.ValueChanged += (sender, args)
			=> { checkBoxLooseMoneyOnDeath.Checked = args.NewValue; };
			
		var checkBoxLooseMoneyWhenBusted = AddCheckbox(
			Resources.UI_Settings_Player_LooseMoneyWhenBusted_Title,
			Resources.UI_Settings_Player_LooseMoneyWhenBusted_Description,
			_settingsService.Player.LooseMoneyWhenBusted.Value,
			changed => { _settingsService.Player.LooseMoneyWhenBusted.Value = changed; });
		
		_settingsService.Player.LooseMoneyWhenBusted.ValueChanged += (sender, args)
			=> { checkBoxLooseMoneyWhenBusted.Checked = args.NewValue; };
			
		var listItemStartingInventory = AddListItem(
			Resources.UI_Settings_Player_StartingInventory_Title,
			Resources.UI_Settings_Player_StartingInventory_Description,
			(item, index) => { _settingsService.Player.StartingInventory.Value = item; },
			_settingsService.Player.GetStartingInventoryValues()
			);

		_settingsService.Player.StartingInventory.ValueChanged += (sender, args)
			=> { listItemStartingInventory.SelectedItem = args.NewValue; };

		var listItemBustChance = AddListItem(
			Resources.UI_Settings_Trafficking_BustChance_Title,
			Resources.UI_Settings_Trafficking_BustChance_Description,
			(item, index) => { _settingsService.Trafficking.BustChance.Value = item; },
			_settingsService.Trafficking.GetBustChanceValues()
			);

		_settingsService.Trafficking.BustChance.ValueChanged += (sender, args)
			=> { listItemBustChance.SelectedItem = args.NewValue; };

		var checkBoxDiscoverDealer = AddCheckbox(
			Resources.UI_Settings_Trafficking_DiscoverDealer_Title,
			Resources.UI_Settings_Trafficking_DiscoverDealer_Description,
			_settingsService.Trafficking.DiscoverDealer.Value,
			changed => { _settingsService.Trafficking.DiscoverDealer.Value = changed; });
		
		_settingsService.Trafficking.DiscoverDealer.ValueChanged += (sender, args)
			=> { checkBoxDiscoverDealer.Checked = args.NewValue; };
			
		var listItemWantedLevel = AddListItem(
			Resources.UI_Settings_Trafficking_WantedLevel_Title,
			Resources.UI_Settings_Trafficking_WantedLevel_Description,
			(item, index) => { _settingsService.Trafficking.WantedLevel.Value = item; },
			_settingsService.Trafficking.GetWantedLevelValues()
			);

		_settingsService.Trafficking.WantedLevel.ValueChanged += (sender, args)
			=> { listItemWantedLevel.SelectedItem = args.NewValue; };

	}
}
