//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDW.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSDW.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; mission has started..
        /// </summary>
        internal static string Mission_Information_Started {
            get {
                return ResourceManager.GetString("Mission.Information.Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; mission has stopped..
        /// </summary>
        internal static string Mission_Information_Stopped {
            get {
                return ResourceManager.GetString("Mission.Information.Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occurred..
        /// </summary>
        internal static string Trafficking_Error_Critical {
            get {
                return ResourceManager.GetString("Trafficking.Error.Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~b~Press ~INPUT_CONTEXT~ ~w~to look at the goods..
        /// </summary>
        internal static string Trafficking_HelpText_DealMenu {
            get {
                return ResourceManager.GetString("Trafficking.HelpText.DealMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had to flee from the cops!.
        /// </summary>
        internal static string Trafficking_Notification_Bust_Message {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Bust.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUST!.
        /// </summary>
        internal static string Trafficking_Notification_Bust_Subject {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Bust.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey dude, if you are near {0} stop by, I have the best products at the best price!.
        /// </summary>
        internal static string Trafficking_Notification_Discovery_Message {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Discovery.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings.
        /// </summary>
        internal static string Trafficking_Notification_Discovery_Subject {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Discovery.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was made cold, the store is closed for the time being!.
        /// </summary>
        internal static string Trafficking_Notification_Iced_Message {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Iced.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICED!.
        /// </summary>
        internal static string Trafficking_Notification_Iced_Subject {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Iced.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Dude, I got some new goods, stop by before they&apos;re gone!.
        /// </summary>
        internal static string Trafficking_Notification_Restock_Message {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Restock.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip-off.
        /// </summary>
        internal static string Trafficking_Notification_Restock_Subject {
            get {
                return ResourceManager.GetString("Trafficking.Notification.Restock.Subject", resourceCulture);
            }
        }
    }
}
