<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>True</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LSDW.Infrastructure\LSDW.Infrastructure.csproj" />
  </ItemGroup>
</Project>
