<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<NoWarn>$(NoWarn);CA1710</NoWarn>
		<UseWindowsForms>True</UseWindowsForms>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="BB84.SourceGenerators">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>
</Project>