//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("LSDW.Tests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.5.29.610")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.5.29.610-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("LSDW.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("LSDW.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.5.29.610")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]

// Generated by the MSBuild WriteCodeFragment class.

