#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LSDW.Abstractions.Infrastructure.Services;

public partial interface ISettingsService
{
  IDealerSettings DealerSettings { get; }
  IMarketSettings MarketSettings { get; }
  IPlayerSettings PlayerSettings { get; }
  ITraffickingSettings TraffickingSettings { get; }
}

public interface IDealerSettings
{
	int GetDownTimeInHours();
  void SetDownTimeInHours(int value);
	bool GetHasArmor();
  void SetHasArmor(bool value);
	bool GetHasWeapons();
  void SetHasWeapons(bool value);
}

public interface IMarketSettings
{
	float GetMaximumDrugValue();
  void SetMaximumDrugValue(float value);
	float GetMinimumDrugValue();
  void SetMinimumDrugValue(float value);
}

public interface IPlayerSettings
{
	float GetExperienceMultiplier();
  void SetExperienceMultiplier(float value);
	bool GetLooseDrugsOnDeath();
  void SetLooseDrugsOnDeath(bool value);
	bool GetLooseMoneyOnDeath();
  void SetLooseMoneyOnDeath(bool value);
	bool GetLooseDrugsWhenBusted();
  void SetLooseDrugsWhenBusted(bool value);
	bool GetLooseMoneyWhenBusted();
  void SetLooseMoneyWhenBusted(bool value);
	int GetInventoryExpansionPerLevel();
  void SetInventoryExpansionPerLevel(int value);
	int GetStartingInventory();
  void SetStartingInventory(int value);
}

public interface ITraffickingSettings
{
	float GetBustChance();
  void SetBustChance(float value);
	int GetWantedLevel();
  void SetWantedLevel(int value);
}
