//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("LSDW.Application.Tests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.6.5.566")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.6.5.566-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("LSDW.Application.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("LSDW.Application.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.6.5.566")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]

// Generated by the MSBuild WriteCodeFragment class.

