using GTA;
using GTA.Math;

namespace LSDW.Activities;

/// <summary>
/// The data <see cref="VanStealing"/> runs on: where a stolen car can be dropped
/// off, and which models are worth stealing. Data only — the behaviour lives in
/// <see cref="VanStealing"/>, exactly as <see cref="DealerRoster"/> stands to
/// <see cref="DealerWorld"/>.
/// </summary>
internal static class VanRoster
{
  /// <summary>
  /// The 24 safe houses. The nearest one becomes the drop-off when a car is stolen.
  /// </summary>
  public static IReadOnlyList<Vector3> SafePlaces { get; } =
    [
      new(692.636f, -1011.985f, 22.464f),
      new(1978.605f, 5171.296f, 47.542f),
      new(1039.071f, 2435.874f, 44.842f),
      new(-1678.03f, -1052.18f, 3.42f),
      new(-619.311f, 346.452f, 85.017f),
      new(212.366f, -3328.39f, 5.704f),
      new(-149.26f, -1662.31f, 32.78f),
      new(165.35f, 6358.57f, 30.75f),
      new(1543.27f, 6335.12f, 23.41f),
      new(3333.46f, 5159.66f, 18.3f),
      new(-3201.04f, 1153.65f, 9.15f),
      new(-1150.75f, -1531.38f, 3.55f),
      new(-1880.93f, -305.6f, 48.54f),
      new(-1214.67f, -353.97f, 36.59f),
      new(61.15f, 159.51f, 104.01f),
      new(739.19f, -536.67f, 26.18f),
      new(216.07f, -937.81f, 23.49f),
      new(135.59f, -1050.79f, 28.5f),
      new(-275.04f, -998.24f, 24.93f),
      new(-188.29f, -1181.99f, 22.54f),
      new(639.23f, -1171.18f, 12.01f),
      new(486.65f, -1333.9f, 28.81f),
      new(364.46f, -1244.92f, 32.11f),
      new(-225.19f, -2657.01f, 5.52f)
    ];

  /// <summary>
  /// The models that can be carrying a stash. <c>VanStealing.MarkNearbyVans</c> tests
  /// every nearby vehicle against this on every tick, so it is a set, not a list:
  /// <see cref="Model"/> is an <see cref="IEquatable{T}"/> struct wrapping its hash,
  /// which makes the lookup O(1) rather than a walk over 187 entries.
  /// </summary>
  public static HashSet<Model> WantedVans { get; } =
    [
      new Model(VehicleHash.Adder),
      new Model(VehicleHash.Alpha),
      new Model(VehicleHash.Ardent),
      new Model(VehicleHash.Autarch),
      new Model(VehicleHash.Banshee),
      new Model(VehicleHash.Banshee2),
      new Model(VehicleHash.BestiaGTS),
      new Model(VehicleHash.Buccaneer),
      new Model(VehicleHash.Buccaneer2),
      new Model(VehicleHash.Buffalo),
      new Model(VehicleHash.Buffalo2),
      new Model(VehicleHash.Brawler),
      new Model(VehicleHash.Brioso),
      new Model(VehicleHash.Buffalo3),
      new Model(VehicleHash.Bullet),
      new Model(VehicleHash.Carbonizzare),
      new Model(VehicleHash.Cheetah),
      new Model(VehicleHash.Cheetah2),
      new Model(VehicleHash.Chino),
      new Model(VehicleHash.Chino2),
      new Model(VehicleHash.Clique),
      new Model(VehicleHash.Cog55),
      new Model(VehicleHash.Cog552),
      new Model(VehicleHash.CogCabrio),
      new Model(VehicleHash.Cognoscenti),
      new Model(VehicleHash.Cognoscenti2),
      new Model(VehicleHash.Comet2),
      new Model(VehicleHash.Coquette),
      new Model(VehicleHash.Coquette2),
      new Model(VehicleHash.Coquette3),
      new Model(VehicleHash.Cyclone),
      new Model(VehicleHash.Deluxo),
      new Model(VehicleHash.Deveste),
      new Model(VehicleHash.Dilettante),
      new Model(VehicleHash.Dominator),
      new Model(VehicleHash.Dodo),
      new Model(VehicleHash.Dominator2),
      new Model(VehicleHash.Dominator3),
      new Model(VehicleHash.Dominator4),
      new Model(VehicleHash.Dubsta),
      new Model(VehicleHash.Dubsta2),
      new Model(VehicleHash.Dubsta3),
      new Model(VehicleHash.Dukes),
      new Model(VehicleHash.Elegy),
      new Model(VehicleHash.Elegy2),
      new Model(VehicleHash.Ellie),
      new Model(VehicleHash.EntityXF),
      new Model(VehicleHash.EntityXXR),
      new Model(VehicleHash.F620),
      new Model(VehicleHash.Faction),
      new Model(VehicleHash.Faction2),
      new Model(VehicleHash.Faction3),
      new Model(VehicleHash.Fagaloa),
      new Model(VehicleHash.Felon),
      new Model(VehicleHash.Felon2),
      new Model(VehicleHash.Feltzer2),
      new Model(VehicleHash.Feltzer3),
      new Model(VehicleHash.FlashGT),
      new Model(VehicleHash.FMJ),
      new Model(VehicleHash.FQ2),
      new Model(VehicleHash.Fugitive),
      new Model(VehicleHash.Furoregt),
      new Model(VehicleHash.Fusilade),
      new Model(VehicleHash.Futo),
      new Model(VehicleHash.Gauntlet),
      new Model(VehicleHash.Gauntlet2),
      new Model(VehicleHash.GB200),
      new Model(VehicleHash.GP1),
      new Model(VehicleHash.GT500),
      new Model(VehicleHash.Hermes),
      new Model(VehicleHash.Hustler),
      new Model(VehicleHash.Impaler),
      new Model(VehicleHash.Impaler2),
      new Model(VehicleHash.Impaler3),
      new Model(VehicleHash.Impaler4),
      new Model(VehicleHash.Imperator),
      new Model(VehicleHash.Imperator2),
      new Model(VehicleHash.Imperator3),
      new Model(VehicleHash.Infernus),
      new Model(VehicleHash.Infernus2),
      new Model(VehicleHash.Intruder),
      new Model(VehicleHash.ItaliGTB),
      new Model(VehicleHash.ItaliGTB2),
      new Model(VehicleHash.ItaliGTO),
      new Model(VehicleHash.Jackal),
      new Model(VehicleHash.Jester),
      new Model(VehicleHash.Jester2),
      new Model(VehicleHash.Jester3),
      new Model(VehicleHash.Kuruma),
      new Model(VehicleHash.Khamelion),
      new Model(VehicleHash.Kuruma2),
      new Model(VehicleHash.LE7B),
      new Model(VehicleHash.Lynx),
      new Model(VehicleHash.Mamba),
      new Model(VehicleHash.Manana),
      new Model(VehicleHash.Massacro),
      new Model(VehicleHash.Massacro2),
      new Model(VehicleHash.Michelli),
      new Model(VehicleHash.Monroe),
      new Model(VehicleHash.Neon),
      new Model(VehicleHash.Nero),
      new Model(VehicleHash.Nero2),
      new Model(VehicleHash.Ninef),
      new Model(VehicleHash.Ninef2),
      new Model(VehicleHash.Omnis),
      new Model(VehicleHash.Oracle),
      new Model(VehicleHash.Oracle2),
      new Model(VehicleHash.Osiris),
      new Model(VehicleHash.Pariah),
      new Model(VehicleHash.Penumbra),
      new Model(VehicleHash.Penetrator),
      new Model(VehicleHash.Pfister811),
      new Model(VehicleHash.Primo),
      new Model(VehicleHash.Primo2),
      new Model(VehicleHash.Prototipo),
      new Model(VehicleHash.Raiden),
      new Model(VehicleHash.RapidGT),
      new Model(VehicleHash.RapidGT2),
      new Model(VehicleHash.RapidGT3),
      new Model(VehicleHash.Raptor),
      new Model(VehicleHash.Reaper),
      new Model(VehicleHash.Retinue),
      new Model(VehicleHash.Revolter),
      new Model(VehicleHash.Ruston),
      new Model(VehicleHash.SabreGT),
      new Model(VehicleHash.SabreGT2),
      new Model(VehicleHash.Savestra),
      new Model(VehicleHash.Schafter2),
      new Model(VehicleHash.SC1),
      new Model(VehicleHash.Schafter3),
      new Model(VehicleHash.Schlagen),
      new Model(VehicleHash.Schwarzer),
      new Model(VehicleHash.Sentinel),
      new Model(VehicleHash.Sentinel2),
      new Model(VehicleHash.Sentinel3),
      new Model(VehicleHash.Serrano),
      new Model(VehicleHash.Seven70),
      new Model(VehicleHash.Sheava),
      new Model(VehicleHash.Specter),
      new Model(VehicleHash.Specter2),
      new Model(VehicleHash.Stalion),
      new Model(VehicleHash.Stafford),
      new Model(VehicleHash.Stalion2),
      new Model(VehicleHash.Stinger),
      new Model(VehicleHash.StingerGT),
      new Model(VehicleHash.Streiter),
      new Model(VehicleHash.Stromberg),
      new Model(VehicleHash.SultanRS),
      new Model(VehicleHash.Superd),
      new Model(VehicleHash.Surano),
      new Model(VehicleHash.T20),
      new Model(VehicleHash.Tailgater),
      new Model(VehicleHash.Tampa),
      new Model(VehicleHash.Taipan),
      new Model(VehicleHash.Tampa2),
      new Model(VehicleHash.Tampa3),
      new Model(VehicleHash.Tempesta),
      new Model(VehicleHash.Tezeract),
      new Model(VehicleHash.Toros),
      new Model(VehicleHash.Tropos),
      new Model(VehicleHash.Tulip),
      new Model(VehicleHash.Turismo2),
      new Model(VehicleHash.Turismor),
      new Model(VehicleHash.Tyrant),
      new Model(VehicleHash.Tyrus),
      new Model(VehicleHash.Vacca),
      new Model(VehicleHash.Vagner),
      new Model(VehicleHash.Vamos),
      new Model(VehicleHash.Verlierer2),
      new Model(VehicleHash.Vestra),
      new Model(VehicleHash.Vigero),
      new Model(VehicleHash.Virgo),
      new Model(VehicleHash.Virgo2),
      new Model(VehicleHash.Viseris),
      new Model(VehicleHash.Visione),
      new Model(VehicleHash.Voltic),
      new Model(VehicleHash.Windsor),
      new Model(VehicleHash.Windsor2),
      new Model(VehicleHash.XLS),
      new Model(VehicleHash.XA21),
      new Model(VehicleHash.XLS2),
      new Model(VehicleHash.Yosemite),
      new Model(VehicleHash.Z190),
      new Model(VehicleHash.Zentorno),
      new Model(VehicleHash.Zion),
      new Model(VehicleHash.Zion2),
      new Model(VehicleHash.ZType)
    ];
}
