//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Los.Santos.Dope.Wars")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023 BoBoBaSs84")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The modification is an attempt to bring the \"trade\" game mechanics from Chinatown" +
    " Wars to the fictional state of San Andreas.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.5.14.1117")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.5.14.1117-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("Los.Santos.Dope.Wars")]
[assembly: System.Reflection.AssemblyTitleAttribute("Los.Santos.Dope.Wars")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.5.14.1117")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/BoBoBaSs84/Los.Santos.Dope.Wars")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Los.Santos.Dope.Wars.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

