//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSDW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The are the settings for the LSDW modification..
        /// </summary>
        internal static string UI_SettingsMenu_Description {
            get {
                return ResourceManager.GetString("UI.SettingsMenu.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will saved on close..
        /// </summary>
        internal static string UI_SettingsMenu_Subtitle {
            get {
                return ResourceManager.GetString("UI.SettingsMenu.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string UI_SettingsMenu_Title {
            get {
                return ResourceManager.GetString("UI.SettingsMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Money: {0}.
        /// </summary>
        internal static string UI_SideMenu_Subtitle_Buy {
            get {
                return ResourceManager.GetString("UI.SideMenu.Subtitle.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Money: {0}.
        /// </summary>
        internal static string UI_SideMenu_Subtitle_Sell {
            get {
                return ResourceManager.GetString("UI.SideMenu.Subtitle.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string UI_SideMenu_Title_Buy {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string UI_SideMenu_Title_Give {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string UI_SideMenu_Title_Retrieve {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string UI_SideMenu_Title_Sell {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string UI_SideMenu_Title_Store {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        internal static string UI_SideMenu_Title_Take {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to sell instead of buying?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Buy {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to take something back?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Give {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to store something?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Retrieve {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to buy instead of selling?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Sell {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to retrieve something?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Store {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to give something back?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Take {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string UI_Switch_Item_Title_Buy {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        internal static string UI_Switch_Item_Title_Give {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string UI_Switch_Item_Title_Retrieve {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string UI_Switch_Item_Title_Sell {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string UI_Switch_Item_Title_Store {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string UI_Switch_Item_Title_Take {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Take", resourceCulture);
            }
        }
    }
}
