//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("BoBoBaSs84")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023 BoBoBaSs84")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The modification is an attempt to bring the \"trade\" game mechanics from Chinatown" +
    " Wars to the fictional state of San Andreas.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.6.11.681")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.6.11.681-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("Los.Santos.Dope.Wars")]
[assembly: System.Reflection.AssemblyTitleAttribute("LSDW.Presentation")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.6.11.681")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/BoBoBaSs84/Los.Santos.Dope.Wars")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("LSDW.Presentation.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

