//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDW.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSDW.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days it will take for the dealer to return after he has fled or been killed..
        /// </summary>
        internal static string UI_Settings_Dealer_DownTimeInHours_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Dealer.DownTimeInHours.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down time in hours.
        /// </summary>
        internal static string UI_Settings_Dealer_DownTimeInHours_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Dealer.DownTimeInHours.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the dealer wear armor?.
        /// </summary>
        internal static string UI_Settings_Dealer_HasArmor_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Dealer.HasArmor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is wearing armor?.
        /// </summary>
        internal static string UI_Settings_Dealer_HasArmor_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Dealer.HasArmor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the dealer carry one or more weapons?.
        /// </summary>
        internal static string UI_Settings_Dealer_HasWeapons_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Dealer.HasWeapons.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the dealer armed?.
        /// </summary>
        internal static string UI_Settings_Dealer_HasWeapons_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Dealer.HasWeapons.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After how many hours does the dealer&apos;s drug offer change?.
        /// </summary>
        internal static string UI_Settings_Market_InventoryChangeInterval_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Market.InventoryChangeInterval.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory change interval.
        /// </summary>
        internal static string UI_Settings_Market_InventoryChangeInterval_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Market.InventoryChangeInterval.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of a drug, serves as a multiplier to the nominal market value..
        /// </summary>
        internal static string UI_Settings_Market_MaximumDrugPrice_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Market.MaximumDrugPrice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum drug value.
        /// </summary>
        internal static string UI_Settings_Market_MaximumDrugPrice_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Market.MaximumDrugPrice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value of a drug, serves as a multiplier to the nominal market value..
        /// </summary>
        internal static string UI_Settings_Market_MinimumDrugPrice_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Market.MinimumDrugPrice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum drug value.
        /// </summary>
        internal static string UI_Settings_Market_MinimumDrugPrice_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Market.MinimumDrugPrice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After how many hours does the current drug price change?.
        /// </summary>
        internal static string UI_Settings_Market_PriceChangeInterval_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Market.PriceChangeInterval.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price change interval.
        /// </summary>
        internal static string UI_Settings_Market_PriceChangeInterval_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Market.PriceChangeInterval.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How likely is it that a dealer will have a special offer..
        /// </summary>
        internal static string UI_Settings_Market_SpecialOfferChance_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Market.SpecialOfferChance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offer chance.
        /// </summary>
        internal static string UI_Settings_Market_SpecialOfferChance_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Market.SpecialOfferChance.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The experience value multiplier, which is to be applied at each experience gain..
        /// </summary>
        internal static string UI_Settings_Player_ExperienceMultiplier_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.ExperienceMultiplier.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience multiplier.
        /// </summary>
        internal static string UI_Settings_Player_ExperienceMultiplier_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.ExperienceMultiplier.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number with which the inventory increases with each level up..
        /// </summary>
        internal static string UI_Settings_Player_InventoryExpansionPerLevel_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.InventoryExpansionPerLevel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory expansion per level.
        /// </summary>
        internal static string UI_Settings_Player_InventoryExpansionPerLevel_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.InventoryExpansionPerLevel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the player looses the drugs he is currently carrying when he gets wasted?.
        /// </summary>
        internal static string UI_Settings_Player_LooseDrugsOnDeath_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseDrugsOnDeath.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose drugs on death?.
        /// </summary>
        internal static string UI_Settings_Player_LooseDrugsOnDeath_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseDrugsOnDeath.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the player looses the drugs he is currently carrying when he gets busted?.
        /// </summary>
        internal static string UI_Settings_Player_LooseDrugsWhenBusted_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseDrugsWhenBusted.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose drugs when busted?.
        /// </summary>
        internal static string UI_Settings_Player_LooseDrugsWhenBusted_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseDrugsWhenBusted.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the player looses the drug money he is currently carrying when he gets wasted?.
        /// </summary>
        internal static string UI_Settings_Player_LooseMoneyOnDeath_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseMoneyOnDeath.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose drug money on death?.
        /// </summary>
        internal static string UI_Settings_Player_LooseMoneyOnDeath_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseMoneyOnDeath.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the player looses the drug money he is currently carrying when he gets busted?.
        /// </summary>
        internal static string UI_Settings_Player_LooseMoneyWhenBusted_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseMoneyWhenBusted.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose drug money when busted?.
        /// </summary>
        internal static string UI_Settings_Player_LooseMoneyWhenBusted_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.LooseMoneyWhenBusted.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the starting inventory or the base value of the inventory..
        /// </summary>
        internal static string UI_Settings_Player_StartingInventory_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Player.StartingInventory.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting inventory.
        /// </summary>
        internal static string UI_Settings_Player_StartingInventory_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Player.StartingInventory.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How likely is a DEA raid after the deal is done?.
        /// </summary>
        internal static string UI_Settings_Trafficking_BustChance_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Trafficking.BustChance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust chance.
        /// </summary>
        internal static string UI_Settings_Trafficking_BustChance_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Trafficking.BustChance.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do the dealers have to be found first or do they appear immediately on the map?.
        /// </summary>
        internal static string UI_Settings_Trafficking_DiscoverDealer_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Trafficking.DiscoverDealer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to discover dealer?.
        /// </summary>
        internal static string UI_Settings_Trafficking_DiscoverDealer_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Trafficking.DiscoverDealer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the mugshot level for a DEA raid?.
        /// </summary>
        internal static string UI_Settings_Trafficking_WantedLevel_Description {
            get {
                return ResourceManager.GetString("UI.Settings.Trafficking.WantedLevel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted level.
        /// </summary>
        internal static string UI_Settings_Trafficking_WantedLevel_Title {
            get {
                return ResourceManager.GetString("UI.Settings.Trafficking.WantedLevel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will saved on close..
        /// </summary>
        internal static string UI_SettingsMenu_Name {
            get {
                return ResourceManager.GetString("UI.SettingsMenu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string UI_SettingsMenu_Title {
            get {
                return ResourceManager.GetString("UI.SettingsMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Money: {0}.
        /// </summary>
        internal static string UI_SideMenu_Name_Buy {
            get {
                return ResourceManager.GetString("UI.SideMenu.Name.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Money: {0}.
        /// </summary>
        internal static string UI_SideMenu_Name_Sell {
            get {
                return ResourceManager.GetString("UI.SideMenu.Name.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string UI_SideMenu_Title_Buy {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string UI_SideMenu_Title_Give {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string UI_SideMenu_Title_Sell {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        internal static string UI_SideMenu_Title_Take {
            get {
                return ResourceManager.GetString("UI.SideMenu.Title.Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to sell instead of buying?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Buy {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to take something back?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Give {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to buy instead of selling?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Sell {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to give something back?.
        /// </summary>
        internal static string UI_Switch_Item_Description_Take {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Description.Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string UI_Switch_Item_Title_Buy {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        internal static string UI_Switch_Item_Title_Give {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string UI_Switch_Item_Title_Sell {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string UI_Switch_Item_Title_Take {
            get {
                return ResourceManager.GetString("UI.Switch.Item.Title.Take", resourceCulture);
            }
        }
    }
}
