<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<UseWindowsForms>True</UseWindowsForms>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\LSDW.Application\LSDW.Application.csproj" />
		<ProjectReference Include="..\LSDW.Infrastructure\LSDW.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BB84.SourceGenerators">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="LemonUI.SHVDN3" ExcludeAssets="runtime" />
	</ItemGroup>
</Project>