#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LSDW.Infrastructure.Services;

internal sealed partial class SettingsService
{
	public void Load()
	{
		int valueDownTimeInHours = GetValue("DEALER", "DOWNTIMEINHOURS", Dealer.DownTimeInHours.Value);
		SetValue("DEALER", "DOWNTIMEINHOURS", valueDownTimeInHours);

		bool valueHasArmor = GetValue("DEALER", "HASARMOR", Dealer.HasArmor.Value);
		SetValue("DEALER", "HASARMOR", valueHasArmor);

		bool valueHasWeapons = GetValue("DEALER", "HASWEAPONS", Dealer.HasWeapons.Value);
		SetValue("DEALER", "HASWEAPONS", valueHasWeapons);

		int valueInventoryChangeInterval = GetValue("MARKET", "INVENTORYCHANGEINTERVAL", Market.InventoryChangeInterval.Value);
		SetValue("MARKET", "INVENTORYCHANGEINTERVAL", valueInventoryChangeInterval);

		float valueMaximumDrugPrice = GetValue("MARKET", "MAXIMUMDRUGPRICE", Market.MaximumDrugPrice.Value);
		SetValue("MARKET", "MAXIMUMDRUGPRICE", valueMaximumDrugPrice);

		float valueMinimumDrugPrice = GetValue("MARKET", "MINIMUMDRUGPRICE", Market.MinimumDrugPrice.Value);
		SetValue("MARKET", "MINIMUMDRUGPRICE", valueMinimumDrugPrice);

		int valuePriceChangeInterval = GetValue("MARKET", "PRICECHANGEINTERVAL", Market.PriceChangeInterval.Value);
		SetValue("MARKET", "PRICECHANGEINTERVAL", valuePriceChangeInterval);

		float valueSpecialOfferChance = GetValue("MARKET", "SPECIALOFFERCHANCE", Market.SpecialOfferChance.Value);
		SetValue("MARKET", "SPECIALOFFERCHANCE", valueSpecialOfferChance);

		float valueExperienceMultiplier = GetValue("PLAYER", "EXPERIENCEMULTIPLIER", Player.ExperienceMultiplier.Value);
		SetValue("PLAYER", "EXPERIENCEMULTIPLIER", valueExperienceMultiplier);

		int valueInventoryExpansionPerLevel = GetValue("PLAYER", "INVENTORYEXPANSIONPERLEVEL", Player.InventoryExpansionPerLevel.Value);
		SetValue("PLAYER", "INVENTORYEXPANSIONPERLEVEL", valueInventoryExpansionPerLevel);

		bool valueLooseDrugsOnDeath = GetValue("PLAYER", "LOOSEDRUGSONDEATH", Player.LooseDrugsOnDeath.Value);
		SetValue("PLAYER", "LOOSEDRUGSONDEATH", valueLooseDrugsOnDeath);

		bool valueLooseDrugsWhenBusted = GetValue("PLAYER", "LOOSEDRUGSWHENBUSTED", Player.LooseDrugsWhenBusted.Value);
		SetValue("PLAYER", "LOOSEDRUGSWHENBUSTED", valueLooseDrugsWhenBusted);

		bool valueLooseMoneyOnDeath = GetValue("PLAYER", "LOOSEMONEYONDEATH", Player.LooseMoneyOnDeath.Value);
		SetValue("PLAYER", "LOOSEMONEYONDEATH", valueLooseMoneyOnDeath);

		bool valueLooseMoneyWhenBusted = GetValue("PLAYER", "LOOSEMONEYWHENBUSTED", Player.LooseMoneyWhenBusted.Value);
		SetValue("PLAYER", "LOOSEMONEYWHENBUSTED", valueLooseMoneyWhenBusted);

		int valueStartingInventory = GetValue("PLAYER", "STARTINGINVENTORY", Player.StartingInventory.Value);
		SetValue("PLAYER", "STARTINGINVENTORY", valueStartingInventory);

		float valueBustChance = GetValue("TRAFFICKING", "BUSTCHANCE", Trafficking.BustChance.Value);
		SetValue("TRAFFICKING", "BUSTCHANCE", valueBustChance);

		bool valueDiscoverDealer = GetValue("TRAFFICKING", "DISCOVERDEALER", Trafficking.DiscoverDealer.Value);
		SetValue("TRAFFICKING", "DISCOVERDEALER", valueDiscoverDealer);

		int valueWantedLevel = GetValue("TRAFFICKING", "WANTEDLEVEL", Trafficking.WantedLevel.Value);
		SetValue("TRAFFICKING", "WANTEDLEVEL", valueWantedLevel);

	}
}
