<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\LSDW.Application\LSDW.Application.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BB84.SourceGenerators">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>