name: Build and Tests .NET Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2
      
    - name: Restore NuGet Packages
      run: nuget restore Los.Santos.Dope.Wars.sln
      
    - name: Build
      run: msbuild Los.Santos.Dope.Wars.sln /t:restore,build /p:Configuration="Release"
      
    - name: Test
      working-directory: LSDW.Tests\bin\x64\Release
      run: vstest.console.exe .\tests\LSDW.Tests\bin\x64\Release\LSDW.Tests.dll .\tests\LSDW.Core.Tests\bin\x64\Release\LSDW.Core.Tests.dll
